---
- name: Deploy Monitoring Stack
  hosts: monitoring_servers
  become: true
  roles:
    - docker
    - monitoring_base
    - prometheus
    - grafana
    - alertmanager
    - nut_exporter

- name: Deploy Node Exporter
  hosts: node_exporter_targets
  become: true
  roles:
    - node_exporter
