---
# Base directories
monitoring_base_dir: "/opt/monitoring"
config_base_dir: "{{ monitoring_base_dir }}/config"
data_base_dir: "{{ monitoring_base_dir }}/data"

# Docker configuration
docker_compose_dir: "{{ monitoring_base_dir }}/compose"

# Prometheus configuration
prometheus_port: 9090
prometheus_data_dir: "{{ data_base_dir }}/prometheus"
prometheus_config_dir: "{{ config_base_dir }}/prometheus"

# Grafana configuration
grafana_port: 3000
grafana_admin_user: "{{ vault_grafana_admin_user }}"
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_data_dir: "{{ data_base_dir }}/grafana"
grafana_config_dir: "{{ config_base_dir }}/grafana"
grafana_allow_sign_up: "false"

# AlertManager configuration
alertmanager_port: 9093
alertmanager_config_dir: "{{ config_base_dir }}/alertmanager"
alertmanager_data_dir: "{{ data_base_dir }}/alertmanager"
alertmanager_enabled: "{{ vault_slack_webhook_url is defined and vault_slack_webhook_url != '' }}"

# NUT configuration
nut_enabled: true
nut_exporter_port: 9199
nut_host: "{{ vault_nut_host }}"
nut_port: "{{ vault_nut_port }}"
nut_username: "{{ vault_nut_username }}"
nut_password: "{{ vault_nut_password }}"
