---
- name: Include prometheus.prometheus.node_exporter role
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: 1.8.2
    node_exporter_web_disable_exporter_metrics: false
    node_exporter_web_listen_address: "0.0.0.0:9100"
    node_exporter_enabled_collectors:
      - systemd
      - cpu
      - meminfo
      - diskstats
      - filesystem
      - netdev
