---
# Copy Prometheus configuration
- name: Copy prometheus config
  ansible.builtin.template:
    src: monitoring/prometheus/prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    mode: "0644"
  notify: restart prometheus

# Copy Docker Compose file
- name: Copy Prometheus Docker Compose file
  template:
    src: "monitoring/prometheus/docker-compose.yml.j2"
    dest: "{{ docker_compose_dir }}/prometheus/docker-compose.yml"
    mode: "0644"

# Deploy Prometheus
- name: Deploy Prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}/prometheus"
    files:
      - docker-compose.yml
    state: present

# Create Prometheus rules directory
- name: Create Prometheus rules directory
  file:
    path: "{{ prometheus_config_dir }}/rules"
    state: directory
    mode: "0755"
  when: alertmanager_enabled

# Copy Prometheus alert rules
- name: Copy Prometheus alert rules
  template:
    src: monitoring/prometheus/rules/node_alerts.yml.j2
    dest: "{{ prometheus_config_dir }}/rules/node_alerts.yml"
    mode: "0644"
  notify: restart prometheus
  when: alertmanager_enabled

# Copy NUT alert rules
- name: Copy NUT alert rules
  template:
    src: monitoring/prometheus/rules/nut_alerts.yml.j2
    dest: "{{ prometheus_config_dir }}/rules/nut_alerts.yml"
    mode: "0644"
  notify: restart prometheus
  when: alertmanager_enabled and (nut_enabled | bool)

# Ensure prometheus is running
- name: Ensure prometheus is running
  ansible.builtin.docker_container:
    name: prometheus
    state: started
    restart_policy: unless-stopped
